### ISSUE TITLE
登录api是否已失效

### ISSUE THREAD

**Issue by xszqxszq** [nnnewb/NEMCore#1]
无论是手机号登录还是邮箱登录都会rasie这个：
`nemcore.exceptions.NetEaseError: 当前登录失败，请稍后再试`

**Comment by nnnewb** [comment]
有段时间没看了，一会儿我去和musicbox的登录接口比对下。

**Comment by nnnewb** [comment]
https://github.com/darknessomi/musicbox/issues/872

加入 `countrycode` 后出现 code=250 当前登陆失败

考虑抄一下 https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/module/login.js

抽空搞

**Comment by nnnewb** [comment]
发现加入 cookie `os: pc` 之后登录恢复正常

**Comment by nnnewb** [comment]
已更新 0.1.6 修复了问题。
